/**
 * Food Inflammation Index (FII) — a per-food inflammatory-potential score computed
 * from composition, adapted from the Food Inflammation Index idea (Wang 2024) to the
 * per-100g columns this archive holds.
 *
 * For one food we read a small set of parameters (fii-parameters.json): an anti-
 * inflammatory side — fat quality (MUFA+PUFA − SFA−trans, scored once so a food's
 * saturated and unsaturated fractions don't cancel), fibre, vitamins C and E,
 * magnesium and (when known) total polyphenols — and a pro-inflammatory side, free
 * sugar and sodium. Each present parameter is standardised against an OPEN reference
 * distribution computed from the public-domain USDA corpus (inflammation-reference.json,
 * regenerated by scripts/build-inflammation-reference.mjs) — a robust z-score, clamped —
 * then combined as a direction-weighted mean. That raw score is standardised again
 * against the corpus to land on the −2 (most anti) … +2 (most pro) axis the medallion
 * already uses.
 *
 * The referent is computed openly from composition data; this is deliberately NOT the
 * licensed Dietary Inflammatory Index — no DII per-parameter effect-score constants are
 * used and the index is never labelled "DII". Every figure is an estimate.
 *
 * The arithmetic here is mirrored by scripts/build-inflammation-reference.mjs and pinned
 * by fii.test.ts so the engine and the referent it reads cannot drift.
 */
import type { NutrientVector } from './types';
import { round, clamp } from './num';
import paramsData from '../data/fii-parameters.json';
import referenceData from '../data/inflammation-reference.json';

interface FiiParam {
  nutrient: string;
  dir: number;
  weight: number;
}
const PARAMS = (paramsData.parameters as FiiParam[]);
const CLAMP_Z: number = paramsData.clampZ;
const REF = referenceData as {
  params: Record<string, { center: number; scale: number; n: number }>;
  fiiRaw: { center: number; scale: number; n: number };
};

export interface FoodFII {
  /** Per-food inflammatory potential on the −2 (anti) … +2 (pro) axis. */
  tag: number;
  /** Fraction of parameters the food supplied (0..1) — a per-food confidence. */
  coverage: number;
}

/**
 * Per-100g value of one parameter for a food, or undefined when the food lacks the
 * datum (treated as unknown, never zero). `fatQuality_g` is derived from the fat
 * fractions; `polyphenol_mg` is carried on the vector (merged from Phenol-Explorer).
 * Mirrors valueOf in scripts/build-inflammation-reference.mjs.
 */
function valueOf(n: NutrientVector, key: string): number | undefined {
  if (key === 'fatQuality_g') {
    const parts = [n.monoFat_g, n.polyFat_g, n.satFat_g, n.transFat_g];
    if (!parts.some((v) => Number.isFinite(v))) return undefined;
    return (n.monoFat_g || 0) + (n.polyFat_g || 0) - (n.satFat_g || 0) - (n.transFat_g || 0);
  }
  if (key === 'freeSugar_g') {
    // Estimate the free (non-intrinsic) sugar from composition: a whole food's
    // sugar travels with fibre, and the 1:2 fibre:free-sugar dual quality ratio
    // treats up to 2 g sugar per 1 g fibre as matrix-bound — so only the excess
    // beyond 2·fibre is scored as free sugar. Undefined when the food has no sugar
    // datum (unknown, never zero); missing fibre is treated as 0 (no cover).
    if (!Number.isFinite(n.sugar_g)) return undefined;
    const fibre = Number.isFinite(n.fiber_g) ? (n.fiber_g as number) : 0;
    return Math.max(0, (n.sugar_g as number) - 2 * fibre);
  }
  const v = (n as Record<string, number | undefined>)[key];
  return Number.isFinite(v) ? (v as number) : undefined;
}

/**
 * Compute a food's inflammatory potential from its per-100g nutrients, or null when
 * none of the parameters are present (no scorable composition) or the reference
 * distribution is degenerate (a non-finite standardised value).
 */
export function foodFII(n: NutrientVector | null | undefined): FoodFII | null {
  if (!n) return null;
  let sum = 0;
  let wsum = 0;
  let present = 0;
  for (const p of PARAMS) {
    const v = valueOf(n, p.nutrient);
    if (v === undefined) continue;
    const ref = REF.params[p.nutrient];
    if (!ref) continue;
    const z = clamp((v - ref.center) / ref.scale, -CLAMP_Z, CLAMP_Z);
    sum += p.dir * p.weight * z;
    wsum += p.weight;
    present += 1;
  }
  if (wsum <= 0) return null;
  const standardised = (sum / wsum - REF.fiiRaw.center) / REF.fiiRaw.scale;
  if (!Number.isFinite(standardised)) return null;
  return { tag: clamp(round(standardised, 1), -2, 2), coverage: present / PARAMS.length };
}
